spring.application.name=urlShortener

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/url_shortener
spring.datasource.username=postgres
spring.datasource.password=charan1234
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.data.redis.host=localhost
spring.data.redis.port=6379

ai.api.url=http://localhost:8080/mock-ai/analyze-url
ai.api.key=dummy-key

server.error.include-stacktrace=never

